database:
    wallet: Wallet_BPK3181NCIYDUJMQ
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@bpk3181nciydujmq_medium
    user: uninadev
    password: Unidevtest4010$
    schema: uninadev

application:
    version: 1.0.0
    loginEnabled: true
    menuViews:
        magazzini: false
        ordini-packaging: true
        ordini-spedizione: true



