database:
    wallet: Wallet_BPK3181NCIYDUJMQ
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@bpk3181nciydujmq_medium
    user: uninaDelivery
    password: UnidevProd4010$
    schema: uninaDelivery
