/*
 *  Trigger per il controllo della data di inizio e fine dell'impegno
 *  di un mezzo
 */

/*

create table MezzoDiTrasporto (
    Id integer generated by default as identity not null, --pk
    Targa varchar2(255 char) not null, -- unique
    TipoMezzo varchar2(255 char) not null, --enum Treno, Camion, Furgone, Auto, Moto, Bicicletta
    IdGruppoCorriere integer not null,
    constraint PkMezzoDiTrasporto primary key (id),
    constraint UkMezzoDiTrasportoTarga unique (Targa),
    constraint CkMezzoDiTrasportoTipoMezzo check( TipoMezzo in ('Treno', 'Camion', 'Furgone', 'Auto', 'Moto', 'Bicicletta')),
    constraint WeakRelGruppoCorriere foreign key (IdGruppoCorriere) references GruppoCorriere (Id) on delete cascade
);

create table ImpegnoMezzo
(
    Id         integer not null, --pk
    IdMezzo    integer not null,
    DataInizio date    not null,
    DataFine   date, -- se non valorizzata si intende fino a data indefinita
    constraint PkImpegnoMezzo primary key (Id),
    constraint FkImpegnoMezzoIdMezzo foreign key (IdMezzo) references MezzoDiTrasporto (Id),
    --dataFine se valorizzato deve essere maggiore di datainizio
    constraint CkImpegnoMezzoDataFine check ( DataFine is null or (DataInizio <= DataFine) )
);
 */

create or replace trigger CkImpegnoMezzoDateRange
before insert or update on ImpegnoMezzo
for each row
declare
    cnt integer;
begin

    select count(*) into cnt
    from impegnomezzo
    where idMezzo = :old.idMezzo and id <> :old.id and
        ( (:new.DataFine is null and :new.DataInizio between DataInizio and DataFine ) or
            (:new.DataFine is not null and
                (
                   (:new.DataInizio between DataInizio and DataFine) or
                   (:new.DataFine between DataInizio and DataFine) or
                   (:new.DataInizio <= DataInizio and :new.DataFine >= DataFine)
                )
            )
        );

    if cnt > 0 then
        RAISE_APPLICATION_ERROR(-20001, 'Impossibile inserire o aggiornare l''impegno del mezzo ' || :old.idMezzo || ' perche'' in conflitto con un altro impegno');
    end if;
end;