create table CatalogoProdotti (
    Id integer generated by default on null as identity not null, --pk
    CodiceEAN varchar2(13 char) not null, --codice univoco, deve essere sempre lungo 13 caratteri
    Nome varchar2(255 char) not null,
    Descrizione varchar2(255 char) not null,
    URLPhoto varchar2(255 char) not null,
    Tipo varchar2(20 byte) not null, --enum Abbigliamento, Alimentari, Elettronica, Casa, Sport, Giardino, Altro
    Prezzo double precision not null,
    Peso number(12,2) not null,
    Larghezza number,
    Altezza number,
    Profondita number,
    Pericolosita varchar2(20 byte) not null, --enum Nessuna, Infiammabile, Esplosivo, Tossico, Chimico, Corrosivo, Infettante, Radioattivo
    constraint PkCatalogoProdotti primary key (id),
    constraint UqCatalogoProdottiCodiceEAN unique (CodiceEAN),
    constraint CkCatalogoProdottiCodiceEAN check (length(CodiceEAN) = 13), --IdVincolo: VI.03
    constraint CkCatalogoProdottiPericolosita check (Pericolosita in ('Nessuna', 'Infiammabile', 'Esplosivo', 'Tossico', 'Chimico', 'Corrosivo', 'Infettante', 'Radioattivo')),
    constraint CkCatalogoProdottiTipo check( Tipo in ('Abbigliamento', 'Alimentari', 'Elettrodomestici', 'Elettronica', 'Casa', 'Sport', 'Giardino', 'Altro') )
);