/*
    Nome: DettaglioOrdine
    Descrizione: contiene i dati dei prodotti ordinati e le relative quantità e la filiale di riferimento. La tabella viene popolata dal sistema
        che aggiorna la filiale di riferimento in base alla giacenza in magazzino
 */
create table DettaglioOrdine (
    Id integer generated by default on null as identity not null,
    IdOrdine integer not null,
    IdProdotto integer not null,
    Quantita integer not null, -- deve essere maggiore di zero
    FlagCompletato char(1) default 'N' not null, -- Y se il dettaglio è stato completato, N altrimenti
    FlagQuantitaDisponibile char(1) default 'Y' not null, -- Y se la quantità richiesta è disponibile, N altrimenti
    --IdFilialeRiferimento integer, -- filiale di riferimento per la gestione del dettaglio ordine
    --IdMagazzinoRiferimento integer,
    --DataAssegnazione DATE,
    constraint PkDettaglioOrdine primary key (Id),
    constraint UqDettaglioOrdineIdOrdineIdProdotto unique (IdOrdine, IdProdotto), --IdVincolo: VI.14
    constraint WeakRelDettaglioOrdineIdOrdine foreign key (IdOrdine) references OrdineCliente (Id) on delete cascade,
    constraint FkDettaglioOrdineIdProdotto foreign key (IdProdotto) references CatalogoProdotti (Id),
    constraint CkDettaglioOrdineQuantita check (Quantita > 0), --IdVincolo: VI.15
    constraint CkDettaglioOrdineFlagCompletato check (FlagCompletato in ('Y', 'N')),
    constraint CkDettaglioOrdineFlagQuantitaDisponibile check (FlagQuantitaDisponibile in ('Y', 'N'))
);