create table Filiale (
    Id integer generated by default on null as identity not null, --pk
    Nome varchar2(50) not null,
    IdOrg integer not null,
    Localita integer not null,
    constraint PkFiliale primary key (id),
    constraint UqFilialeNomeOrg unique (Nome, IdOrg),
    constraint WeakRelOrg foreign key (IdOrg) references Org (Id) on delete cascade,
    constraint FkLocalita foreign key (Localita) references Indirizzo (Id)
);