create table Magazzino (
    Id integer generated by default on null as identity not null, --pk
    Nome varchar2(255 char) not null,
    IdIndirizzo integer not null,
    IdFiliale integer not null,
    constraint PkMagazzino primary key (id),
    constraint UqMagazzinoNomeFiliale unique (Nome, IdFiliale),
    constraint FkMagazzinoIndirizzo foreign key (IdIndirizzo) references Indirizzo (id),
    constraint FkMagazzinoFiliale foreign key (IdFiliale) references Filiale (id)
);