create table MerceStoccata (
    Id integer generated by default on null as identity not null, --pk
    IdProdotto integer not null,
    QuantitaReale integer not null, -- deve essere sempre maggiore di zero
    QuantitaPrenotata integer default 0 not null, -- deve essere sempre maggiore o uguale a zero
    QuantitaDisponibile integer generated always as (QuantitaReale - QuantitaPrenotata) virtual not null, --IdVincolo: CL.01
    IdMagazzino integer not null,
    SettoreMagazzino char(1),
    constraint PkMerceStoccata primary key (Id),
    constraint FkMerceStoccataIdProdotto foreign key (IdProdotto) references CatalogoProdotti (id),
    constraint FkMerceStoccataIdMagazzino foreign key (IdMagazzino) references Magazzino (id),
    constraint UqMerceStoccataIdProdottoIdMagazzino unique (IdProdotto, IdMagazzino), --IdVincolo: VI.04
    constraint CkMerceStoccataQuantitaReale check (QuantitaReale > 0), --IdVincolo: VI.05
    constraint CkMerceStoccataQuantitaPrenotata check (QuantitaPrenotata >= 0) --IdVincolo: VI.06
);