/*
    Nome: OrdineDiLavoroSpedizionePacchi
    Descrizione: riporta i pacchi che compongono l'ordine di lavoro di tipo 'Spedizione'
 */
create table OrdineDiLavoroSpedizionePacchi (
    Id integer generated by default as identity not null,
    IdOrdineDiLavoroSpedizione integer not null,
    IdPacco integer not null,
    constraint PkOrdineDiLavoroSpedizionePacchi primary key (Id),
    constraint WeakRelOrdineDiLavoroSpedizionePacchiIdOrdineDiLavoroSpedizione foreign key (IdOrdineDiLavoroSpedizione) references OrdineDiLavoroSpedizione (Id) on delete cascade,
    constraint FkOrdineDiLavoroSpedizionePacchiIdPacco foreign key (IdPacco) references Pacco (Id)
);