create table Org (
    Id integer generated by default on null as identity not null, --pk
    Paese varchar2(255 char) not null,
    RagioneSociale varchar2(255 char) not null,
    PartitaIVA varchar2(255 char), -- se valorizzata deve essere di 11 cifre
    SedeLegaleIndirizzo integer not null,
    constraint PkOrg primary key (id),
    constraint CkOrgPartitaIVA check (PartitaIVA is null or (length(PartitaIVA) = 11)), --IdVincolo: VI.02
    constraint FkOrgSedeLegaleIndirizzo foreign key (SedeLegaleIndirizzo) references Indirizzo (Id)
);