create table Pacco (
    Id integer generated by default on null as identity not null,
    CodicePacco varchar2(50) not null, -- codice univoco alfanumerico
    Peso number(12,2) not null, -- peso del pacco in kg, solitamente il peso unitario per il numero di prodotti ordinati
    IdMagazzino integer not null, --magazzino da cui prelevare il pacco
    IdIndirizzoDestinazione integer not null, -- indirizzo di destinazione del pacco
    IdOrdineLavoroOrigine integer not null, -- ordine di lavoro di tipo 'Packaging' che genera il pacco
    IdSpedizione integer not null, -- spedizione a cui è destinato il pacco
    constraint PkPacco primary key (Id),
    constraint UqPaccoCodicePacco unique (CodicePacco),
    constraint FkPaccoIdMagazzino foreign key (IdMagazzino) references Magazzino (Id),
    constraint FkPaccoIdIndirizzoDestinazione foreign key (IdIndirizzoDestinazione) references Indirizzo (Id),
    constraint FkPaccoIdOrdineLavoroOrigine foreign key (IdOrdineLavoroOrigine) references OrdineDiLavoroPackaging (Id),
    constraint FkPaccoIdSpedizione foreign key (IdSpedizione) references Spedizione (Id)
);