/*
    Nome: PackagingDetails
    Descrizione: riporta i dettagli per quali parti di ordine del cliente occorre effettuare il package
 */
create table PackagingDetails
(
    Id integer generated by default on null as identity not null,
    IdOrdineDiLavoroPackaging integer not null,
    IdDettaglioOrdine integer not null,
    IdMerceStoccataRiferimento integer not null,
    Pericolosita varchar2(20 byte) default 'Nessuna' not null, --enum Nessuna, Infiammabile, Esplosivo, Tossico, Chimico, Corrosivo, Infettante, Radioattivo
	CodicePropostaPacco integer not null,
    constraint PkPackagingDetails primary key (Id),
    constraint WeakRelPackagingDetailsIdOrdineDiLavoroPackaging foreign key (IdOrdineDiLavoroPackaging) references OrdineDiLavoroPackaging (Id) on delete cascade,
    constraint FkPackagingDetailsIdDettaglioOrdine foreign key (IdDettaglioOrdine) references DettaglioOrdine (Id),
    constraint FkPackagingDetailsIdMerceStoccataRiferimento foreign key (IdMerceStoccataRiferimento) references MerceStoccata (Id),
    constraint CkPackagingDetailsPericolosita check (Pericolosita in ('Nessuna', 'Infiammabile', 'Esplosivo', 'Tossico', 'Chimico', 'Corrosivo', 'Infettante', 'Radioattivo'))
);